<?php
/**
 * Copyright © 2018 Acme. All rights reserved.
 * @license GPLv3
 */

/**
 * @var \Acme\StoreLocator\Block\Html\Link $block
 * @var \Magento\Framework\Escaper $escaper
 */

// @codingStandardsIgnoreFile
?>
<li class="level0 level-top<?php if($block->isCurrent()) echo ' active'; ?>">
    <a href="<?= $escaper->escapeHtml($block->getHref()); ?>" title="<?= $escaper->escapeHtml($block->getLabel()); ?>" class="level-top">
        <?= $escaper->escapeHtml($block->getLabel()); ?>
    </a>
</li>
